### ISSUE TITLE
LSP with Mix Gleam seems to not working

### ISSUE THREAD

**Issue by sclee15** [gleam-lang/vscode-gleam#37]
First of all, I think Gleam and its ecosystem have potential.
Wonderful work!

I tried to use VSCode Gleam with a mix_gleam project.
It looks like type inferences and real-time syntax error checking are not working.
However, the gleam compilation with mix is ok.

Thank you.

**Comment by lpil** [comment]
Hello! Thank you for the kind words.

The LSP doesn't know anything about unofficial build tools so there's no way to use it with them. If it can't compile the code and extract the required information then it cannot surface this to the editor.

In future we may be able to support other tools but it'd be a degraded experience compared to using the Gleam build tool (as it would get new information after running `mix` rather than with each character typed) and it'd likely need to come after Mix etc get built-in support for Gleam. The MixGleam project is fab but is a stop-gap solution that hacks around not having the required support in Mix.
