### ISSUE TITLE
display error along with any type information

### ISSUE THREAD

**Issue by orvitpng** [gleam-lang/vscode-gleam#83]
Currently, when there is an error, it will only display that error and no other information. This is especially inconvenient in situations where maybe you're trying to get the type of function parameters, and all it will show is an error. I propose, like in many other languages, the error is shown below the regular hover data.

**Comment by lpil** [comment]
Hello! This repo is unrelated to the behaviour of the language server, it would be an issue for the compiler repo.

Gleam and the LS are very new and fault tolerant analysis was added a few weeks ago. Because of this it is very coarse grained currently, but over time it will become more fine grained and have the features you want from other ones that are many years old.

**Comment by orvitpng** [comment]
> Hello! This repo is unrelated to the behaviour of the language server, it would be an issue for the compiler repo.
> 
> Gleam and the LS are very new and fault tolerant analysis was added a few weeks ago. Because of this it is very coarse grained currently, but over time it will become more fine grained and have the features you want from other ones that are many years old.

I'm not sure that's the case. The feature I'm requesting is implemented perfectly fine in glas, and other extensions seem to handle it fine without modifications to the language server itself

**Comment by lpil** [comment]
This extension doesn't do anything but pass through to the language server.

glas is a different language server with no relationship to the Gleam Language Server or the core team.
